################################# Default configuration ###################
baseURL = "https://spaceout.dev"
title = "SpaceOut | Bridging Startup and Tech"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

################################# Outputs #################################
# hugo outputs
[outputs]
home = ["HTML"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/logo.svg"
logo_width = "150px"
# Meta data
description = "Bridging Startup and Tech"
author = "SpaceOut"
# Contact Information
mobile = ""
email = ""
location = ""
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

############################# social site ########################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"


######################### english navigation #############################
# main menu
[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About"
URL = "about"
weight = 2

[[Languages.en.menu.main]]
name = "Project"
URL = "project"
weight = 3

[[Languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.en.menu.main]]
weight = 5
name = "Pages"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "FAQ"
  URL = "faq"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "Pricing"
  URL = "pricing"

  [[Languages.en.menu.main]]
  parent = "Pages"
  name = "Service"
  URL = "service"
  
[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 6


# footer menu
[[Languages.en.menu.footer]]
name = "About"
URL = "about"
weight = 1

[[Languages.en.menu.footer]]
name = "Project"
URL = "project"
weight = 2

[[Languages.en.menu.footer]]
name = "Service"
URL = "service"
weight = 3

[[Languages.en.menu.footer]]
name = "Pricing"
URL = "pricing"
weight = 4

[[Languages.en.menu.footer]]
name = "FAQ"
URL = "faq"
weight = 5

[[Languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6
